name: Waka Readme
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.waka_f868942d-21d8-4823-bb3d-01ce43a71a97 }}
          GH_TOKEN: ${{ secrets.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 }}